### ISSUE TITLE
KeyError: 'sha1'

### ISSUE THREAD

**Issue by he7d3r** [halfak/Mediawiki-Utilities#19]
```python
from mw.api import Session
from mw.lib import reverts
session = Session("https://pt.wikipedia.org/w/api.php")
reverts.api.check_rev(session, {'revid':40679746,'pageid':69874})
reverts.api.check_rev(session, {'revid': 40679734, 'pageid': 24386})
```
works fine, however
```python
reverts.api.check_rev(session, {'revid':40679748,'pageid':40677})
```
causes the following error:
```python
Traceback (most recent call last):
  File "demonstrate_scorer_on_rc.py", line 79, in <module>
    reverted = 0 if reverts.api.check_rev(session, rev) is None else 1
  File "<mypath>/lib/python3.4/site-packages/mw/lib/reverts/api.py", line 40, in check_rev
    return check(session, rev_id, page_id=page_id, **kwargs)
  File "<mypath>/lib/python3.4/site-packages/mw/lib/reverts/api.py", line 115, in check
    for revert in detect(checksum_revisions, radius=radius):
  File "<mypath>/lib/python3.4/site-packages/mw/lib/reverts/functions.py", line 40, in detect
    for checksum, revision in checksum_revisions:
  File "<mypath>/lib/python3.4/site-packages/mw/lib/reverts/api.py", line 110, in <genexpr>
    ((rev['sha1'], rev) for rev in past_revs),
KeyError: 'sha1'
```

**Comment by he7d3r** [comment]
I noticed the same problem with other revisions for which there is a sha1:
* [40840140](https://pt.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=ids|timestamp|user|size|sha1&revids=40840140)
* [40841893](https://pt.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=ids|timestamp|user|size|sha1&revids=40841893)
* [40843260](https://pt.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=ids|timestamp|user|size|sha1&revids=40843260)

**Comment by he7d3r** [comment]
The page 40677 contains the revision 40327912, which has an attribute `"sha1hidden": ""` (and a `sha1` which seems to be visible to sysops only):
https://pt.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=ids|timestamp|user|size|sha1&rvlimit=20&pageids=40677
However it is far from the revision we are interested in. The error does not happen if I run
```python
reverts.api.check_rev(session, {'revid':40679748,'pageid':40677}, radius=7)
```
but it happens when I increase the radius to 8:
```python
reverts.api.check_rev(session, {'revid':40679748,'pageid':40677}, radius=8)
```

Using a big radius should not be a reason for failure, because 40679748 was reverted by the revision which is right after it in the history (40686393), and a radius of 2 is enough to detect that (BTW: shouldn't it radius 1 be enough too?). In other words, we have something like this:
A[sha1hidden] --> B --> C --> D --> E --> F --> G --> **H** --> **I**[reverted] --> **H**

**Comment by halfak** [comment]
Fixed in https://github.com/halfak/Mediawiki-Utilities/commit/a2936671ddc0b52ace012636fc5854c562c64ce8

And updated in v0.4.11
